name: gethub
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Architecture
  flutter_riverpod: ^1.0.4

  # For Model
  freezed_annotation: ^2.1.0
  equatable: ^2.0.3
  json_serializable: ^6.3.1

  # For storage
  shared_preferences: ^2.0.15

  # For l10n
  intl: ^0.17.0

  # For UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For gen
  build_runner: ^2.2.0

  # For Model
  freezed: ^2.1.0+1
  
  # For Analyzer
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
